### ISSUE TITLE
Is Latest version of zed-unity-livelink support theZED SDK 4.0.6 version ?

### ISSUE THREAD

**Issue by LinJason0209** [stereolabs/zed-unity-livelink#7]
Hi I try to using the  latest version of zed-unity-livelink to catch more ZED camera. But I always can't run the ZED_Unity_Livelink_Fusion.exe with configure Json file, which is created with ZED 360 under SDK 4.0.6 version.

And I found someone message in the ZED Community is say "The zed unity livelink plugin is not updated to support the newest 4.0.6 ZED SDK." Link: https://community.stereolabs.com/t/zed-unity-livelink-with-functionality-similar-to-the-zed-unity-plugin/3402
Is it true?

**Comment by SLJLMacarit** [comment]
Yes, the last version supports both 4.0.5 and 4.0.6. It was not clear, we updated the readme.
Thanks for the report!
